In [5]:
try:
    import wrds
except ImportError:
    !pip install wrds

In [6]:
conn = wrds.Connection()

Enter your WRDS username [Owner]:hchan1
Enter your password:········
WRDS recommends setting up a .pgpass file.
You can find more info here:
https://www.postgresql.org/docs/9.5/static/libpq-pgpass.html.
Loading library list...
Done

In [8]:
import random

libraries = conn.list_libraries()

libraries[:10]

['wrds_lib_internal',
 'ppubsamp_d4d_new',
 'ktmine',
 'ibescorp',
 'contrib_char_returns_new',
 'taq',
 'secsamp_all_new',
 'compd',
 'compgd',
 'preqsamp_all_new']

In [9]:
library = "crsp"

tables = conn.list_tables(library = library)

tables[:10]

['ccm_lookup',
 'ccm_qvards',
 'ccmxpf_linktable',
 'ccmxpf_lnkhist',
 'ccmxpf_lnkrng',
 'ccmxpf_lnkused',
 'comphead',
 'comphist',
 'compmaster',
 'cst_hist']

In [10]:
library = "crsp"

table = "dse"

conn.describe_table(library = library, table  = table).head()

Approximately 11479800 rows in crsp.dse.

     name  nullable              type
0   event      True           VARCHAR
1    date      True              DATE
2  hsicmg      True  DOUBLE PRECISION
3  hsicig      True  DOUBLE PRECISION
4  comnam      True           VARCHAR

In [12]:
library = "crsp"
table = "dsf"
columns = ["cusip, permno, permco, date, prc, openprc, bid, bidlo, ask, askhi, vol, ret, retx"]
obs = 20

conn.get_table(library = library, table = table, columns = columns, obs = obs)

,cusip,permno,permco,date,prc,openprc,bid,bidlo,ask,askhi,vol,ret,retx
0,33738R88,14804.0,54165.0,2015-11-23,18.000000,17.950001,17.969999,17.924999,18.000000,18.059900,315050.0,-0.004975,-0.004975
1,33738R88,14804.0,54165.0,2015-11-24,17.900000,17.809999,17.879999,17.719999,17.900000,17.910000,209802.0,-0.005556,-0.005556
2,33738R88,14804.0,54165.0,2015-11-25,18.000000,17.910000,17.990000,17.900000,18.000000,18.030001,256605.0,0.005587,0.005587
3,33738R88,14804.0,54165.0,2015-11-27,17.920000,18.000000,17.959999,17.868999,17.990000,18.000000,94675.0,-0.004444,-0.004444
4,33738R88,14804.0,54165.0,2015-11-30,18.130100,18.090000,18.129999,17.978701,18.139999,18.170000,214931.0,0.011724,0.011724
5,33738R88,14804.0,54165.0,2015-12-01,18.280001,18.190001,18.260000,18.140100,18.280001,18.280001,159009.0,0.008268,0.008268
6,33738R88,14804.0,54165.0,2015-12-02,18.139999,18.209999,18.129999,18.100500,18.139999,18.250000,229672.0,-0.007659,-0.007659
7,33738R88,14804.0,54165.0,2015-12-03,18.129999,18.160000,18.100000,18.020100,18.129999,18.320000,157212.0,-0.000551,-0.000551
8,33738R88,14804.0,54165.0,2015-12-04,18.350000,18.070000,18.340000,18.040100,18.350000,18.360001,240914.0,0.012135,0.012135
9,33738R88,14804.0,54165.0,2015-12-07,18.250000,18.180000,18.250000,18.180000,18.290001,18.300800,551821.0,-0.005450,-0.005450
10,33738R88,14804.0,54165.0,2015-12-08,18.069901,18.059999,18.040001,17.950100,18.070000,18.079901,202815.0,-0.009868,-0.009868
11,33738R88,14804.0,54165.0,2015-12-09,17.980000,18.049999,17.950001,17.876101,18.000000,18.153999,222766.0,-0.004975,-0.004975
12,33738R88,14804.0,54165.0,2015-12-10,17.920000,17.900000,17.920000,17.900000,17.940001,18.049900,337021.0,-0.003337,-0.003337
13,33738R88,14804.0,54165.0,2015-12-11,17.600000,17.750000,17.590000,17.600000,17.629999,17.770399,225916.0,-0.017857,-0.017857
14,33738R88,14804.0,54165.0,2015-12-14,17.660000,17.680000,17.629999,17.500000,17.670000,17.730000,259495.0,0.003409,0.003409
15,33738R88,14804.0,54165.0,2015-12-15,17.830000,17.690001,17.790001,17.500000,17.820000,17.899900,637104.0,0.009626,0.009626
16,33738R88,14804.0,54165.0,2015-12-16,18.059999,17.969999,18.020000,17.840000,18.059999,18.070000,405542.0,0.012900,0.012900
17,33738R88,14804.0,54165.0,2015-12-17,17.870001,18.070000,17.860001,17.860001,17.900000,18.070000,326678.0,-0.010520,-0.010520
18,33738R88,14804.0,54165.0,2015-12-18,17.820000,17.840000,17.790001,17.790001,17.830000,17.940001,1769330.0,-0.002798,-0.002798
19,33738R88,14804.0,54165.0,2015-12-21,17.889999,17.940001,17.870001,17.770000,17.879999,18.030001,467723.0,0.003928,0.003928